# Generated by Django 4.2.8 on 2023-12-22 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobi_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_of_joining',
            new_name='date_joined',
        ),
    ]
