# Generated by Django 4.2.8 on 2023-12-23 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mobi_app', '0002_rename_date_of_joining_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_exercises', to='mobi_app.exercise'),
        ),
        migrations.AlterField(
            model_name='sessionexercise',
            name='workout_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_exercises', to='mobi_app.workoutsession'),
        ),
        migrations.AlterField(
            model_name='set',
            name='session_exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='mobi_app.sessionexercise'),
        ),
        migrations.AlterField(
            model_name='templateexercise',
            name='workout_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_exercises', to='mobi_app.workouttemplate'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='workout_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to='mobi_app.workouttemplate'),
        ),
        migrations.AlterField(
            model_name='workouttemplate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
