# Generated by Django 4.2.8 on 2023-12-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobi_app', '0003_alter_sessionexercise_exercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
