# Generated by Django 4.2.8 on 2023-12-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobi_app', '0004_alter_workouttemplate_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
