# Generated by Django 4.2.8 on 2024-01-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobi_app', '0005_alter_workoutsession_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='reps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
