# Generated by Django 4.2.8 on 2024-01-21 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobi_app', '0008_alter_exercise_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsession',
            name='workout_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to='mobi_app.workouttemplate'),
        ),
    ]
