# Generated by Django 4.2.8 on 2024-01-31 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobi_app', '0010_alter_workoutsession_workout_template_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
